name: Test & Deploy

on:
  pull_request:
    branches: [ master ]
  push:
    branches:  [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Latest Repo
        uses: actions/checkout@master
      - name: Set up JDK 11.5.0
     uses: actions/setup-java@v2
     with:
      java-version: '11'
      distribution: 'adopt'

  ### Maven ###
  # - name: Grant execute permission for Maven
  # run: chmod +x mvnw
  #
  # - name: Build with Maven
  # run: ./mvnw package

  ### Gradle ###
  - name: Grant execute permission for gradlew
    run: chmod +x gradlew

  - name: Build with Gradle
    run: ./gradlew build


  - name: Docker build
    run: |
  docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
  docker build -t docker-test .
  docker tag docker-test testbuild/git-action-test:latest
  docker push testbuild-hub/git-action-test:latest