name: Docker Image CI

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build and push Docker images
      uses: docker/build-push-action@v3.1.1

